// Code generated by MockGen. DO NOT EDIT.
// Source: serenity/reporting/reporter.go
//
// Generated by this command:
//
//	mockgen -source=serenity/reporting/reporter.go -destination=serenity/reporting/mocks/mock_reporter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	reporting "github.com/nchursin/serenity-go/serenity/reporting"
	gomock "go.uber.org/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// OnStepFinish mocks base method.
func (m *MockReporter) OnStepFinish(stepResult reporting.TestResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStepFinish", stepResult)
}

// OnStepFinish indicates an expected call of OnStepFinish.
func (mr *MockReporterMockRecorder) OnStepFinish(stepResult any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStepFinish", reflect.TypeOf((*MockReporter)(nil).OnStepFinish), stepResult)
}

// OnStepStart mocks base method.
func (m *MockReporter) OnStepStart(stepDescription string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStepStart", stepDescription)
}

// OnStepStart indicates an expected call of OnStepStart.
func (mr *MockReporterMockRecorder) OnStepStart(stepDescription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStepStart", reflect.TypeOf((*MockReporter)(nil).OnStepStart), stepDescription)
}

// OnTestFinish mocks base method.
func (m *MockReporter) OnTestFinish(result reporting.TestResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnTestFinish", result)
}

// OnTestFinish indicates an expected call of OnTestFinish.
func (mr *MockReporterMockRecorder) OnTestFinish(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTestFinish", reflect.TypeOf((*MockReporter)(nil).OnTestFinish), result)
}

// OnTestStart mocks base method.
func (m *MockReporter) OnTestStart(testName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnTestStart", testName)
}

// OnTestStart indicates an expected call of OnTestStart.
func (mr *MockReporterMockRecorder) OnTestStart(testName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTestStart", reflect.TypeOf((*MockReporter)(nil).OnTestStart), testName)
}

// SetOutput mocks base method.
func (m *MockReporter) SetOutput(w io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOutput", w)
}

// SetOutput indicates an expected call of SetOutput.
func (mr *MockReporterMockRecorder) SetOutput(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutput", reflect.TypeOf((*MockReporter)(nil).SetOutput), w)
}

// MockTestResult is a mock of TestResult interface.
type MockTestResult struct {
	ctrl     *gomock.Controller
	recorder *MockTestResultMockRecorder
	isgomock struct{}
}

// MockTestResultMockRecorder is the mock recorder for MockTestResult.
type MockTestResultMockRecorder struct {
	mock *MockTestResult
}

// NewMockTestResult creates a new mock instance.
func NewMockTestResult(ctrl *gomock.Controller) *MockTestResult {
	mock := &MockTestResult{ctrl: ctrl}
	mock.recorder = &MockTestResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestResult) EXPECT() *MockTestResultMockRecorder {
	return m.recorder
}

// Attachments mocks base method.
func (m *MockTestResult) Attachments() []reporting.Attachment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attachments")
	ret0, _ := ret[0].([]reporting.Attachment)
	return ret0
}

// Attachments indicates an expected call of Attachments.
func (mr *MockTestResultMockRecorder) Attachments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attachments", reflect.TypeOf((*MockTestResult)(nil).Attachments))
}

// Duration mocks base method.
func (m *MockTestResult) Duration() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Duration")
	ret0, _ := ret[0].(float64)
	return ret0
}

// Duration indicates an expected call of Duration.
func (mr *MockTestResultMockRecorder) Duration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Duration", reflect.TypeOf((*MockTestResult)(nil).Duration))
}

// Error mocks base method.
func (m *MockTestResult) Error() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockTestResultMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockTestResult)(nil).Error))
}

// Name mocks base method.
func (m *MockTestResult) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTestResultMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTestResult)(nil).Name))
}

// Status mocks base method.
func (m *MockTestResult) Status() reporting.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(reporting.Status)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockTestResultMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockTestResult)(nil).Status))
}
