// Code generated by MockGen. DO NOT EDIT.
// Source: verity/core/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=verity/core/interfaces.go -destination=verity/core/testing/mocks/mock_activity.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	abilities "github.com/nchursin/verity-bdd/internal/abilities"
	core "github.com/nchursin/verity-bdd/internal/core"
	gomock "go.uber.org/mock/gomock"
)

// MockActor is a mock of Actor interface.
type MockActor struct {
	ctrl     *gomock.Controller
	recorder *MockActorMockRecorder
	isgomock struct{}
}

// MockActorMockRecorder is the mock recorder for MockActor.
type MockActorMockRecorder struct {
	mock *MockActor
}

// NewMockActor creates a new mock instance.
func NewMockActor(ctrl *gomock.Controller) *MockActor {
	mock := &MockActor{ctrl: ctrl}
	mock.recorder = &MockActorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActor) EXPECT() *MockActorMockRecorder {
	return m.recorder
}

// AbilityTo mocks base method.
func (m *MockActor) AbilityTo(ability abilities.Ability) (abilities.Ability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbilityTo", ability)
	ret0, _ := ret[0].(abilities.Ability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AbilityTo indicates an expected call of AbilityTo.
func (mr *MockActorMockRecorder) AbilityTo(ability any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbilityTo", reflect.TypeOf((*MockActor)(nil).AbilityTo), ability)
}

// AnswersTo mocks base method.
func (m *MockActor) AnswersTo(question core.Question[any]) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswersTo", question)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// AnswersTo indicates an expected call of AnswersTo.
func (mr *MockActorMockRecorder) AnswersTo(question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswersTo", reflect.TypeOf((*MockActor)(nil).AnswersTo), question)
}

// AttemptsTo mocks base method.
func (m *MockActor) AttemptsTo(activities ...core.Activity) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range activities {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AttemptsTo", varargs...)
}

// AttemptsTo indicates an expected call of AttemptsTo.
func (mr *MockActorMockRecorder) AttemptsTo(activities ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttemptsTo", reflect.TypeOf((*MockActor)(nil).AttemptsTo), activities...)
}

// Context mocks base method.
func (m *MockActor) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockActorMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockActor)(nil).Context))
}

// Name mocks base method.
func (m *MockActor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockActorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockActor)(nil).Name))
}

// WhoCan mocks base method.
func (m *MockActor) WhoCan(arg0 ...abilities.Ability) core.Actor {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WhoCan", varargs...)
	ret0, _ := ret[0].(core.Actor)
	return ret0
}

// WhoCan indicates an expected call of WhoCan.
func (mr *MockActorMockRecorder) WhoCan(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhoCan", reflect.TypeOf((*MockActor)(nil).WhoCan), arg0...)
}

// MockActivity is a mock of Activity interface.
type MockActivity struct {
	ctrl     *gomock.Controller
	recorder *MockActivityMockRecorder
	isgomock struct{}
}

// MockActivityMockRecorder is the mock recorder for MockActivity.
type MockActivityMockRecorder struct {
	mock *MockActivity
}

// NewMockActivity creates a new mock instance.
func NewMockActivity(ctrl *gomock.Controller) *MockActivity {
	mock := &MockActivity{ctrl: ctrl}
	mock.recorder = &MockActivityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivity) EXPECT() *MockActivityMockRecorder {
	return m.recorder
}

// Description mocks base method.
func (m *MockActivity) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockActivityMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockActivity)(nil).Description))
}

// FailureMode mocks base method.
func (m *MockActivity) FailureMode() core.FailureMode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailureMode")
	ret0, _ := ret[0].(core.FailureMode)
	return ret0
}

// FailureMode indicates an expected call of FailureMode.
func (mr *MockActivityMockRecorder) FailureMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailureMode", reflect.TypeOf((*MockActivity)(nil).FailureMode))
}

// PerformAs mocks base method.
func (m *MockActivity) PerformAs(ctx context.Context, actor core.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformAs", ctx, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformAs indicates an expected call of PerformAs.
func (mr *MockActivityMockRecorder) PerformAs(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformAs", reflect.TypeOf((*MockActivity)(nil).PerformAs), ctx, actor)
}

// MockInteraction is a mock of Interaction interface.
type MockInteraction struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionMockRecorder
	isgomock struct{}
}

// MockInteractionMockRecorder is the mock recorder for MockInteraction.
type MockInteractionMockRecorder struct {
	mock *MockInteraction
}

// NewMockInteraction creates a new mock instance.
func NewMockInteraction(ctrl *gomock.Controller) *MockInteraction {
	mock := &MockInteraction{ctrl: ctrl}
	mock.recorder = &MockInteractionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteraction) EXPECT() *MockInteractionMockRecorder {
	return m.recorder
}

// Description mocks base method.
func (m *MockInteraction) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockInteractionMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockInteraction)(nil).Description))
}

// FailureMode mocks base method.
func (m *MockInteraction) FailureMode() core.FailureMode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailureMode")
	ret0, _ := ret[0].(core.FailureMode)
	return ret0
}

// FailureMode indicates an expected call of FailureMode.
func (mr *MockInteractionMockRecorder) FailureMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailureMode", reflect.TypeOf((*MockInteraction)(nil).FailureMode))
}

// PerformAs mocks base method.
func (m *MockInteraction) PerformAs(ctx context.Context, actor core.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformAs", ctx, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformAs indicates an expected call of PerformAs.
func (mr *MockInteractionMockRecorder) PerformAs(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformAs", reflect.TypeOf((*MockInteraction)(nil).PerformAs), ctx, actor)
}

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
	isgomock struct{}
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// Description mocks base method.
func (m *MockTask) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockTaskMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockTask)(nil).Description))
}

// FailureMode mocks base method.
func (m *MockTask) FailureMode() core.FailureMode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailureMode")
	ret0, _ := ret[0].(core.FailureMode)
	return ret0
}

// FailureMode indicates an expected call of FailureMode.
func (mr *MockTaskMockRecorder) FailureMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailureMode", reflect.TypeOf((*MockTask)(nil).FailureMode))
}

// PerformAs mocks base method.
func (m *MockTask) PerformAs(ctx context.Context, actor core.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformAs", ctx, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformAs indicates an expected call of PerformAs.
func (mr *MockTaskMockRecorder) PerformAs(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformAs", reflect.TypeOf((*MockTask)(nil).PerformAs), ctx, actor)
}

// MockQuestion is a mock of Question interface.
type MockQuestion[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionMockRecorder[T]
	isgomock struct{}
}

// MockQuestionMockRecorder is the mock recorder for MockQuestion.
type MockQuestionMockRecorder[T any] struct {
	mock *MockQuestion[T]
}

// NewMockQuestion creates a new mock instance.
func NewMockQuestion[T any](ctrl *gomock.Controller) *MockQuestion[T] {
	mock := &MockQuestion[T]{ctrl: ctrl}
	mock.recorder = &MockQuestionMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestion[T]) EXPECT() *MockQuestionMockRecorder[T] {
	return m.recorder
}

// AnsweredBy mocks base method.
func (m *MockQuestion[T]) AnsweredBy(ctx context.Context, actor core.Actor) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnsweredBy", ctx, actor)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnsweredBy indicates an expected call of AnsweredBy.
func (mr *MockQuestionMockRecorder[T]) AnsweredBy(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnsweredBy", reflect.TypeOf((*MockQuestion[T])(nil).AnsweredBy), ctx, actor)
}

// Description mocks base method.
func (m *MockQuestion[T]) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockQuestionMockRecorder[T]) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockQuestion[T])(nil).Description))
}
